[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "golang.org/x/xerrors"
  revision = "d61658bd2e18010be0e21349cc92b1b706e35146"

[prune]
  go-tests = true
  unused-packages = true
