// Code generated by "stringer -type ProductID -trimprefix ProductID"; DO NOT EDIT.

package vlp16

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ProductIDHDL32E-33]
	_ = x[ProductIDVLP16-34]
	_ = x[ProductIDPuckLITE-34]
	_ = x[ProductIDPuckHiRes-36]
	_ = x[ProductIDVLP32C-40]
	_ = x[ProductIDVelarray-49]
	_ = x[ProductIDVLS128-99]
}

const (
	_ProductID_name_0 = "HDL32EVLP16"
	_ProductID_name_1 = "PuckHiRes"
	_ProductID_name_2 = "VLP32C"
	_ProductID_name_3 = "Velarray"
	_ProductID_name_4 = "VLS128"
)

var (
	_ProductID_index_0 = [...]uint8{0, 6, 11}
)

func (i ProductID) String() string {
	switch {
	case 33 <= i && i <= 34:
		i -= 33
		return _ProductID_name_0[_ProductID_index_0[i]:_ProductID_index_0[i+1]]
	case i == 36:
		return _ProductID_name_1
	case i == 40:
		return _ProductID_name_2
	case i == 49:
		return _ProductID_name_3
	case i == 99:
		return _ProductID_name_4
	default:
		return "ProductID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
