// Code generated by "stringer -type ReturnMode -trimprefix ReturnMode"; DO NOT EDIT.

package vlp16

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ReturnModeStrongest-55]
	_ = x[ReturnModeLastReturn-56]
	_ = x[ReturnModeDualReturn-57]
}

const _ReturnMode_name = "StrongestLastReturnDualReturn"

var _ReturnMode_index = [...]uint8{0, 9, 19, 29}

func (i ReturnMode) String() string {
	i -= 55
	if i >= ReturnMode(len(_ReturnMode_index)-1) {
		return "ReturnMode(" + strconv.FormatInt(int64(i+55), 10) + ")"
	}
	return _ReturnMode_name[_ReturnMode_index[i]:_ReturnMode_index[i+1]]
}
